name: build-test

on: push

jobs:
  
  linux-build:
    name: ubutu ${{ matrix.debug }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        debug: [ "Debug","Release" ]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.debug }} ..
          make -j2
          ./test

      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu-${{ matrix.debug }}
          path: build/test

  docker-build:
    name: Docker ${{ matrix.conf.name }} ${{ matrix.debug }}
    runs-on: ubuntu-latest
    container: ${{ matrix.conf.cont }}
    strategy:
      fail-fast: false
      matrix:
        debug: [ "Debug","Release" ]
        conf:
          - { cont: "debian:10", name: "deb10", init: "apt-get update && apt-get -y install cmake build-essential"}
          - { cont: "debian:9", name: "deb9", init: "apt-get update && apt-get -y install cmake build-essential"}
          - { cont: "centos:8", name: "cos8", init: ""}
          - { cont: "centos:7", name: "cos7", init: ""}

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          ${{ matrix.conf.init }}
          g++ --version
          cmake --version
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.debug }} ..
          make -j2
          ./test

      - uses: actions/upload-artifact@v2
        with:
          name: Docker-${{ matrix.conf.name }}-${{ matrix.debug }}
          path: build/test

