name: build-test

on: push

jobs:
  
  linux-build:
    name: Linux ubutu ${{ matrix.debug }}
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        debug: [ "Debug","Release" ]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=${{ matrix.debug }} ..
          make -j2
          ./test

      - uses: actions/upload-artifact@v2
        with:
          path: build/test

        